INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('1', 'Mumbai(BOM)', 'Jaipur(JAI)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('2', 'Mumbai(BOM)', 'Jaipur(JAI)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('3', 'Mumbai(BOM)', 'Jaipur(JAI)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('4', 'New Delhi(DEL)', 'Jaipur(JAI)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('5', 'New Delhi(DEL)', 'Jaipur(JAI)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('6', 'New Delhi(DEL)', 'Jaipur(JAI)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('7', 'Goa(GOI)', 'Jaipur(JAI)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('8', 'Goa(GOI)', 'Jaipur(JAI)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('9', 'Goa(GOI)', 'Jaipur(JAI)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('10', 'Pune(PNQ)', 'Jaipur(JAI)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('11', 'Pune(PNQ)', 'Jaipur(JAI)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('12', 'Pune(PNQ)', 'Jaipur(JAI)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('13', 'Kolkata(CCU)', 'Jaipur(JAI)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('14', 'Kolkata(CCU)', 'Jaipur(JAI)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('15', 'Kolkata(CCU)', 'Jaipur(JAI)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('16', 'Banglore(BLR)', 'Jaipur(JAI)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('17', 'Banglore(BLR)', 'Jaipur(JAI)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('18', 'Banglore(BLR)', 'Jaipur(JAI)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('19', 'Chennai(MAA)', 'Jaipur(JAI)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('20', 'Chennai(MAA)', 'Jaipur(JAI)', 'Vistara');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('21', 'Chennai(MAA)', 'Jaipur(JAI)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('22', 'Jaipur(JAI)', 'Mumbai(BOM)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('23', 'Jaipur(JAI)', 'Mumbai(BOM)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('24', 'Jaipur(JAI)', 'Mumbai(BOM)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('25', 'Jaipur(JAI)', 'New Delhi(DEL)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('26', 'Jaipur(JAI)', 'New Delhi(DEL)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('27', 'Jaipur(JAI)', 'New Delhi(DEL)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('28', 'Jaipur(JAI)', 'Goa(GOI)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('29', 'Jaipur(JAI)', 'Goa(GOI)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('30', 'Jaipur(JAI)', 'Goa(GOI)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('31', 'Jaipur(JAI)', 'Pune(PNQ)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('32', 'Jaipur(JAI)', 'Pune(PNQ)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('33', 'Jaipur(JAI)', 'Pune(PNQ)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('34', 'Jaipur(JAI)', 'Kolkata(CCU)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('35', 'Jaipur(JAI)', 'Kolkata(CCU)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('36', 'Jaipur(JAI)', 'Kolkata(CCU)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('37', 'Jaipur(JAI)', 'Banglore(BLR)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('38', 'Jaipur(JAI)', 'Banglore(BLR)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('39', 'Jaipur(JAI)', 'Banglore(BLR)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('40', 'Jaipur(JAI)', 'Chennai(MAA)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('41', 'Jaipur(JAI)', 'Chennai(MAA)', 'Vistara');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('42', 'Jaipur(JAI)', 'Chennai(MAA)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('43', 'Jaipur(JAI)', 'Raipur(RPR)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('44', 'Jaipur(JAI)', 'Raipur(RPR)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('45', 'Jaipur(JAI)', 'Raipur(RPR)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('46', 'Mumbai(BOM)', 'Raipur(RPR)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('47', 'Mumbai(BOM)', 'Raipur(RPR)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('48', 'Mumbai(BOM)', 'Raipur(RPR)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('49', 'New Delhi(DEL)', 'Raipur(RPR)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('50', 'New Delhi(DEL)', 'Raipur(RPR)', 'Vistara');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('51', 'New Delhi(DEL)', 'Raipur(RPR)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('52', 'Goa(GOI)', 'Raipur(RPR)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('53', 'Goa(GOI)', 'Raipur(RPR)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('54', 'Goa(GOI)', 'Raipur(RPR)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('55', 'Pune(PNQ)', 'Raipur(RPR)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('56', 'Pune(PNQ)', 'Raipur(RPR)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('57', 'Pune(PNQ)', 'Raipur(RPR)', 'Vistara');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('58', 'Kolkata(CCU)', 'Raipur(RPR)', 'Soicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('59', 'Kolkata(CCU)', 'Raipur(RPR)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('60', 'Kolkata(CCU)', 'Raipur(RPR)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('61', 'Banglore(BLR)', 'Raipur(RPR)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('62', 'Banglore(BLR)', 'Raipur(RPR)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('63', 'Banglore(BLR)', 'Raipur(RPR)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('64', 'Banglore(BLR)', 'Mumbai(BOM)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('65', 'Banglore(BLR)', 'Mumbai(BOM)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('66', 'Banglore(BLR)', 'Mumbai(BOM)', 'Vistara');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('67', 'Kolkata(CCU)', 'Mumbai(BOM)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('68', 'Kolkata(CCU)', 'Mumbai(BOM)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('69', 'Kolkata(CCU)', 'Mumbai(BOM)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('70', 'Goa(GOI)', 'Mumbai(BOM)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('71', 'Goa(GOI)', 'Mumbai(BOM)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('72', 'Goa(GOI)', 'Mumbai(BOM)', 'Vistara');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('73', 'New Delhi(DEL)', 'Mumbai(BOM)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('74', 'New Delhi(DEL)', 'Mumbai(BOM)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('75', 'New Delhi(DEL)', 'Mumbai(BOM)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('76', 'Pune(PNQ)', 'Mumbai(BOM)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('78', 'Pune(PNQ)', 'Mumbai(BOM)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('79', 'Pune(PNQ)', 'Mumbai(BOM)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('80', 'Chennai(MAA)', 'Mumbai(BOM)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('81', 'Chennai(MAA)', 'Mumbai(BOM)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('82', 'Chennai(MAA)', 'Mumbai(BOM)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('83', 'Goa(GOI)', 'New Delhi(DEL)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('84', 'Goa(GOI)', 'New Delhi(DEL)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('85', 'Goa(GOI)', 'New Delhi(DEL)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('86', 'Pune(PNQ)', 'New Delhi(DEL)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('87', 'Pune(PNQ)', 'New Delhi(DEL)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('88', 'Pune(PNQ)', 'New Delhi(DEL)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('89', 'Kolkata(CCU)', 'New Delhi(DEL)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('90', 'Kolkata(CCU)', 'New Delhi(DEL)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('91', 'Kolkata(CCU)', 'New Delhi(DEL)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('92', 'Banglore(BLR)', 'New Delhi(DEL)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('93', 'Banglore(BLR)', 'New Delhi(DEL)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('94', 'Banglore(BLR)', 'New Delhi(DEL)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('95', 'Surat(STV)', 'New Delhi(DEL)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('96', 'Surat(STV)', 'New Delhi(DEL)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('97', 'Surat(STV)', 'New Delhi(DEL)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('98', 'Lucknow(LKO)', 'New Delhi(DEL)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('99', 'Lucknow(LKO)', 'New Delhi(DEL)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('100', 'Lucknow(LKO)', 'New Delhi(DEL)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('101', 'Raipur(RPR)', 'Jaipur(JAI)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('102', 'Raipur(RPR)', 'Jaipur(JAI)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('103', 'Raipur(RPR)', 'Jaipur(JAI)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('104', 'Raipur(RPR)', 'New Delhi(DEL)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('105', 'Raipur(RPR)', 'New Delhi(DEL)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('106', 'Raipur(RPR)', 'New Delhi(DEL)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('107', 'Raipur(RPR)', 'Mumbai(BOM)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('108', 'Raipur(RPR)', 'Mumbai(BOM)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('109', 'Raipur(RPR)', 'Mumbai(BOM)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('110', 'Raipur(RPR)', 'Pune(PNQ)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('111', 'Raipur(RPR)', 'Pune(PNQ)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('112', 'Raipur(RPR)', 'Pune(PNQ)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('113', 'Raipur(RPR)', 'Goa(GOI)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('114', 'Raipur(RPR)', 'Goa(GOI)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('115', 'Raipur(RPR)', 'Goa(GOI)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('116', 'Raipur(RPR)', 'Kolkata(CCU)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('117', 'Raipur(RPR)', 'Kolkata(CCU)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('118', 'Raipur(RPR)', 'Kolkata(CCU)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('119', 'Raipur(RPR)', 'Banglore(BLR)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('120', 'Raipur(RPR)', 'Banglore(BLR)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('130', 'Raipur(RPR)', 'Banglore(BLR)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('131', 'Banglore(BLR)', 'Allahabad(IXD)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('132', 'Banglore(BLR)', 'Allahabad(IXD)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('133', 'Banglore(BLR)', 'Allahabad(IXD)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('134', 'Kolkata(CCU)', 'Allahabad(IXD)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('135', 'Kolkata(CCU)', 'Allahabad(IXD)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('136', 'Kolkata(CCU)', 'Allahabad(IXD)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('137', 'Goa(GOI)', 'Allahabad(IXD)', 'Spicejet');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('138', 'Goa(GOI)', 'Allahabad(IXD)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('139', 'Goa(GOI)', 'Allahabad(IXD)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('140', 'New Delhi(DEL)', 'Allahabad(IXD)', 'Go First');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('141', 'New Delhi(DEL)', 'Allahabad(IXD)', 'Vistara');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('142', 'New Delhi(DEL)', 'Allahabad(IXD)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('143', 'Mumbai(BOM)', 'Allahabad(IXD)', 'Vistara');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('144', 'Mumbai(BOM)', 'Allahabad(IXD)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('145', 'Mumbai(BOM)', 'Allahabad(IXD)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('146', 'Pune(PNQ)', 'Allahabad(IXD)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('147', 'Pune(PNQ)', 'Allahabad(IXD)', 'Indigo');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('148', 'Pune(PNQ)', 'Allahabad(IXD)', 'Air India');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('149', 'Chennai(MAA)', 'Allahabad(IXD)', 'Air Asia');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('150', 'Chennai(MAA)', 'Allahabad(IXD)', 'GoAir');
INSERT INTO `flights`.`search_table` (`ID`, `To`, `From`, `Flight_Name`) VALUES ('151', 'Chennai(MAA)', 'Allahabad(IXD)', 'Spicejet');
